# Generated by Django 5.0.3 on 2024-05-15 16:01

import django.db.models.deletion
import mcq.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("spaces", "0007_joinrequest"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Collections",
            fields=[
                ("collectionId", models.AutoField(primary_key=True, serialize=False)),
                ("marks", models.IntegerField()),
                ("time_in_minutes", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField(default=mcq.models.time_plus_days)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "spaceId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="spaces.space"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Questions",
            fields=[
                ("questionId", models.AutoField(primary_key=True, serialize=False)),
                ("question", models.TextField()),
                ("option1", models.TextField(default=None)),
                ("option2", models.TextField(default=None)),
                ("option3", models.TextField(default=None)),
                ("option4", models.TextField(default=None)),
                ("correct_answer", models.TextField(default=None)),
                (
                    "collectionId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mcq.collections",
                    ),
                ),
            ],
        ),
    ]
