# Generated by Django 5.0.3 on 2024-05-15 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mcq", "0001_initial"),
        ("spaces", "0007_joinrequest"),
    ]

    operations = [
        migrations.AlterField(
            model_name="collections",
            name="spaceId",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="spaces.space",
                to_field="spaceId",
            ),
        ),
    ]
