# Generated by Django 5.0.3 on 2024-05-15 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mcq", "0002_alter_collections_spaceid"),
    ]

    operations = [
        migrations.AddField(
            model_name="collections",
            name="description",
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name="collections",
            name="name",
            field=models.CharField(default=None, max_length=255),
        ),
    ]
