# Generated by Django 5.0.3 on 2024-05-15 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mcq", "0004_alter_collections_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="collections",
            name="pass_marks",
            field=models.IntegerField(default=0),
        ),
    ]
