# Generated by Django 5.0.3 on 2024-04-03 19:37

import datetime
import django.db.models.deletion
import portal.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("spaces", "0006_alter_notice_created_at_alter_notice_deadline"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Portal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "portalId",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("name", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "submission_start",
                    models.DateTimeField(default=datetime.datetime.now),
                ),
                (
                    "deadline",
                    models.DateTimeField(default=portal.models.time_plus_days),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "space",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="spaces.space",
                        to_field="spaceId",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PortalSubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "portalSubmissionId",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("file_path", models.TextField(default="portal_submissions/")),
                (
                    "submission",
                    models.FileField(
                        upload_to=models.TextField(default="portal_submissions/")
                    ),
                ),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "portal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="portal.portal",
                        to_field="portalId",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
