# Generated by Django 5.0.3 on 2024-04-05 07:12

import portal.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="portalsubmission",
            name="file_path",
        ),
        migrations.AlterField(
            model_name="portalsubmission",
            name="submission",
            field=models.FileField(upload_to=portal.models.get_upload_path),
        ),
    ]
