# Generated by Django 5.0.3 on 2024-05-15 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0003_portal_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="portal",
            name="description",
            field=models.TextField(default=None, null=True),
        ),
    ]
