# Generated by Django 5.0.3 on 2024-04-01 18:19

import django.db.models.deletion
import spaces.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("spaces", "0004_alter_notice_created_at"),
    ]

    operations = [
        migrations.RenameField(
            model_name="notice",
            old_name="NoticeId",
            new_name="noticeId",
        ),
        migrations.AlterField(
            model_name="notice",
            name="created_at",
            field=spaces.models.CustomDateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="notice",
            name="deadline",
            field=spaces.models.CustomDateTimeField(
                default=spaces.models.now_plus_3_days
            ),
        ),
        migrations.AlterField(
            model_name="notice",
            name="space",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="spaces.space",
                to_field="spaceId",
            ),
        ),
    ]
