# Generated by Django 5.0.3 on 2024-04-01 19:27

import spaces.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("spaces", "0005_rename_noticeid_notice_noticeid_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notice",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="notice",
            name="deadline",
            field=models.DateTimeField(default=spaces.models.now_plus_3_days),
        ),
    ]
